project_id = "zroerzpqtyygmiamzkhy"

[functions.imvu-room-chat]
verify_jwt = false

[functions.imvu-user-history]
verify_jwt = false

[functions.imvu-user-presence]
verify_jwt = false

[functions.imvu-monitor-user]
verify_jwt = false
